// Copyright Offene Werkstatt Wädenswil
// SPDX-License-Identifier: MIT

#pragma once

/// @file proto_serializer.h
/// @brief Serializer for pw_protobuf generated messages.
///
/// This serializer works with messages generated by pwpb_proto_library.
/// Each proto generates a struct with:
/// - Proto::Message - the data struct
/// - Proto::MemoryEncoder - encoder for serializing
/// - Proto::StreamDecoder - decoder for deserializing
///
/// Usage:
/// @code
/// #include "my_proto.pwpb.h"
///
/// MyMessage::Message msg{.field = 42};
/// std::array<std::byte, 64> buffer;
///
/// // Serialize
/// auto size = ProtoSerializer<MyMessage>::Serialize(msg, buffer);
/// if (size.ok()) {
///   // buffer contains encoded proto, size.value() is length
/// }
///
/// // Deserialize
/// auto decoded = ProtoSerializer<MyMessage>::Deserialize(
///     pw::ConstByteSpan(buffer.data(), size.value()));
/// if (decoded.ok()) {
///   // decoded.value().field == 42
/// }
/// @endcode

#include "pb_cloud/serializer.h"
#include "pb_cloud/types.h"
#include "pw_bytes/span.h"
#include "pw_result/result.h"
#include "pw_stream/memory_stream.h"

namespace pb::cloud {

/// Serializer for pw_protobuf generated messages.
///
/// @tparam Proto The proto type (e.g., MyMessage from my_message.pwpb.h)
///               Must have Proto::Message, Proto::MemoryEncoder, etc.
template <typename Proto>
struct ProtoSerializer {
  /// The message struct type.
  using Message = typename Proto::Message;

  /// Serialize message to buffer.
  ///
  /// @param value Message to serialize
  /// @param buffer Output buffer (must be large enough for encoded message)
  /// @return Number of bytes written, or error
  static pw::Result<size_t> Serialize(const Message& value,
                                      pw::ByteSpan buffer) {
    typename Proto::MemoryEncoder encoder(buffer);
    pw::Status status = encoder.Write(value);
    if (!status.ok()) {
      return status;
    }
    return encoder.size();
  }

  /// Deserialize bytes to message.
  ///
  /// @param data Encoded proto bytes
  /// @return Decoded message, or error
  static pw::Result<Message> Deserialize(pw::ConstByteSpan data) {
    Message msg{};
    pw::stream::MemoryReader reader(data);
    typename Proto::StreamDecoder decoder(reader);
    pw::Status status = decoder.Read(msg);
    if (!status.ok()) {
      return status;
    }
    return msg;
  }

  /// Content type for protobuf serialization.
  static constexpr ContentType kContentType = ContentType::kStructured;
};

}  // namespace pb::cloud
